### PR TITLE
added multi gameserver suppport

### PR DESCRIPTION
**Pull request by zeroaltud**
since people need it and asked for it

### CODE REVIEW

**Comment by burlone0** [comment]
Why u create a mmcodes.js if u don't use it

**Comment by burlone0** [comment]
and u test it before do the pull request?

**Comment by zeroaltud** [comment]
> and u test it before do the pull request?

yes ofc i did

**Comment by zeroaltud** [comment]
> Why u create a mmcodes.js if u don't use it

it does get used?
image

**Comment by burlone0** [comment]
remove that part

**Comment by zeroaltud** [comment]
> remove that part

nah not gonna work just merge like holy dam

**Review by DorDorFN — COMMENTED** [review]
a

**Pull request closed without merging**
