### PR TITLE
+ Make everything prettier with bootstrap | + Added to the readme

### PR DESCRIPTION
**Pull request by toiletalphamale**
In the readme I added so they could do custom domain but not the most best way (check the new readme please)
>>> 
Added bootstrap to the register and already exist page so they look 10000 times better
>>> 
Burlone rip ur pc hope it revives it self 👍

### CODE REVIEW

**Comment by burlone0** [comment]
Can u send a ss for preview?

**Comment by toiletalphamale** [comment]
> Can u send a ss for preview?

http://api.targeteater.xyz:100/

**Comment by toiletalphamale** [comment]
image
The lutro part is Reload backend its jst that it was for my backend orginaly but i changed it to reload
image
same thing here

**Comment by burlone0** [comment]
uh i don't like the style, if u upgrade it prob i'll merge this

**Pull request closed without merging**
