### PR TITLE
Ability to gain xp using the camp fire in 11.31 and quest (credits MarvelcoOGFN for abit)

### PR DESCRIPTION
**Pull request by andreudev1337**

### CODE REVIEW

**Comment by andreudev1337** [comment]
yeah in 11.31 u get xp when using they

**Comment by MarvelcoOGFN** [comment]
my code !!!!

**Comment by andreudev1337** [comment]
i lil say credits to u :Skull:

**Comment by MarvelcoOGFN** [comment]
> i lil say credits to u :Skull:
> 

I'd like my code to be in my own backend and not in 384849 backends

**Comment by UniqueTomm** [comment]
> > i lil say credits to u :Skull:
> 
> I'd like my code to be in my own backend and not in 384849 backends

then don't make the backend open source lol

**Comment by MarvelcoOGFN** [comment]
> > > i lil say credits to u :Skull:
> > 
> > 
> > I'd like my code to be in my own backend and not in 384849 backends
> 
> then don't make the backend open source lol

umm bro i just dont like people pasting stuff from my backend (even with credit) cause stuff that makes my backend special if it where to be added to other backends it wont be spacial anymore

**Pull request closed without merging**
